"""The per-tile role ladder, generated per project.

A tile's tree range is baked into its symbol, so `kernel::create` needs a literal name and
a runtime index cannot choose between them -- the enumeration is unavoidable.

The header carries no include guard: it is included once per section, and the section is
named by the macro defined immediately before the include.
"""

_BANNER = """// Generated by conifer's AIE backend. Do not edit.
//
// The per-tile role ladder for this project's mapping. No include guard: this file is
// included once per section, and the section is chosen by the macro defined just before
// it (BDT_LADDER_DECL, BDT_LADDER_DEF, BDT_LADDER_CREATE).
//
//   {key}
"""


def ladder(n_tiles, split_axis, merge, tap=0):
    """(declarations, definitions, creates) for one mapping, as lists of lines."""
    decl, defn, create = [], [], []
    if split_axis != "tree" or n_tiles <= 1:
        # One symbol serves every tile: N=1, and every tile of a sample split, which
        # differ only in which samples arrive. The graph creates those in a plain loop.
        return decl, defn, create

    if merge in ("plio", "reduce"):
        for s in range(n_tiles):
            r0 = "0" if s == 0 else ""
            decl.append(f"BDT_DECL_ROLE{r0}({s})")
            defn.append(f"BDT_DEF_ROLE{r0}({s})")
            create.append(f"k[{s}] = kernel::create(bdt_qs_tile_{s});")
        return decl, defn, create

    head = "BDT_DECL_HEAD_TAP" if tap else "BDT_DECL_HEAD"
    head_def = "BDT_DEF_HEAD_TAP" if tap else "BDT_DEF_HEAD"
    decl.append(f"{head}(0)")
    defn.append(f"{head_def}(0)")
    create.append("k[0] = kernel::create(bdt_qs_tile_0);")
    for s in range(1, n_tiles):
        role = "TAIL" if s == n_tiles - 1 else "LINK"
        decl.append(f"BDT_DECL_{role}({s})")
        defn.append(f"BDT_DEF_{role}({s})")
        create.append(f"k[{s}] = kernel::create(bdt_qs_tile_{s});")
    return decl, defn, create


def tile_roles_h(n_tiles, split_axis, merge, tap=0):
    decl, defn, create = ladder(n_tiles, split_axis, merge, tap)
    key = f"n_tiles={n_tiles} split={split_axis} merge={merge} tap={tap}"
    out = [_BANNER.format(key=key)]
    for guard, lines in (
        ("BDT_LADDER_DECL", decl),
        ("BDT_LADDER_DEF", defn),
        ("BDT_LADDER_CREATE", create),
    ):
        out.append(f"#ifdef {guard}")
        out.extend(lines)
        out.append(f"#endif  // {guard}")
        out.append("")
    return "\n".join(out)
